# Generated by Django 4.1 on 2023-03-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profileuser_user_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='user_manager',
        ),
    ]
