# Generated by Django 4.1 on 2023-03-14 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_profileuser_user_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер клієнта')),
            ],
            options={
                'verbose_name': 'Менеджер клієнта',
            },
        ),
    ]
