# Generated by Django 4.1 on 2023-03-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_manageruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='user_manager',
        ),
    ]
