# Generated by Django 3.2.7 on 2021-11-26 12:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва бренду:')),
                ('image_icon', models.ImageField(blank=True, upload_to='brand_icon')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Опис бренду:')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Модель:')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Опис моделі:')),
                ('slug', models.SlugField(unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_model', to='shop.brand', verbose_name='Бренд моделі:')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модель',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Категорія:')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Опис категорії:')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndexLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_one', models.CharField(max_length=10, unique=True, verbose_name='Індекс:')),
                ('name_two', models.CharField(max_length=25, verbose_name='Значення:')),
            ],
            options={
                'verbose_name': 'Індекс навантаження',
                'verbose_name_plural': 'Індекси навантаження',
                'ordering': ['name_one'],
            },
        ),
        migrations.CreateModel(
            name='IndexSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_one', models.CharField(max_length=2, unique=True, verbose_name='Індекс:')),
                ('name_two', models.CharField(max_length=25, verbose_name='Значення:')),
            ],
            options={
                'verbose_name': 'Індекс швидкості',
                'verbose_name_plural': 'Індекси швидкості',
                'ordering': ['name_one'],
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тип:')),
                ('image_icon', models.ImageField(blank=True, upload_to='kind_icon')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Опис:')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Тип',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Сезон:')),
                ('image_icon', models.ImageField(blank=True, upload_to='season_icon')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Опис сезону:')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезон',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.IntegerField(verbose_name='Стан:')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Рік:')),
                ('country', models.CharField(blank=True, max_length=150, verbose_name='Країна:')),
                ('in_stock', models.IntegerField(verbose_name='На складі, шт.:')),
                ('available', models.BooleanField(default=True, verbose_name='В наявності:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість:')),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Нова вартість:')),
                ('recommend', models.BooleanField(default=False, verbose_name='Рекомендуєм:')),
                ('shipy', models.BooleanField(default=False, verbose_name='Шипы')),
                ('lipuchka', models.BooleanField(default=False, verbose_name='Липучка')),
                ('run_flat', models.BooleanField(default=False, verbose_name='RunFlat')),
                ('conti_seal', models.BooleanField(default=False, verbose_name='ContiSeal')),
                ('low_prof', models.BooleanField(default=False, verbose_name='Низк.проф.')),
                ('mad', models.BooleanField(default=False, verbose_name='Грязевые')),
                ('rain', models.BooleanField(default=False, verbose_name='Дождевые')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('choice', models.CharField(blank=True, choices=[('-', '-'), ('Т', 'Т'), ('БК', 'БК'), ('КЛ', 'КЛ'), ('Л/П', 'Л/П')], max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_category', to='shop.category', verbose_name='Категорія:')),
                ('index_load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_index_load', to='shop.indexload', verbose_name='Індекс навантаження:')),
                ('index_speed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_index_speed', to='shop.indexspeed', verbose_name='Індекс швидкості:')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_model', to='shop.brandmodel', verbose_name='Модель:')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='foto', verbose_name='Зображення:')),
                ('tire', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='shop.tire', verbose_name='Резина:')),
            ],
            options={
                'verbose_name': 'Зображення',
                'verbose_name_plural': 'Зображення',
                'ordering': ['tire'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='kind',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_kind', to='shop.kind', verbose_name='Тип категорії:'),
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_model_season', to='shop.season', verbose_name='Сезон моделі'),
        ),
    ]
