# Generated by Django 3.2.7 on 2021-11-26 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTire',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('condition', models.IntegerField(verbose_name='Стан:')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Рік:')),
                ('country', models.CharField(blank=True, max_length=150, verbose_name='Країна:')),
                ('in_stock', models.IntegerField(verbose_name='На складі, шт.:')),
                ('available', models.BooleanField(default=True, verbose_name='В наявності:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість:')),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Нова вартість:')),
                ('recommend', models.BooleanField(default=False, verbose_name='Рекомендуєм:')),
                ('shipy', models.BooleanField(default=False, verbose_name='Шипы')),
                ('lipuchka', models.BooleanField(default=False, verbose_name='Липучка')),
                ('run_flat', models.BooleanField(default=False, verbose_name='RunFlat')),
                ('conti_seal', models.BooleanField(default=False, verbose_name='ContiSeal')),
                ('low_prof', models.BooleanField(default=False, verbose_name='Низк.проф.')),
                ('mad', models.BooleanField(default=False, verbose_name='Грязевые')),
                ('rain', models.BooleanField(default=False, verbose_name='Дождевые')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('choice', models.CharField(blank=True, choices=[('-', '-'), ('Т', 'Т'), ('БК', 'БК'), ('КЛ', 'КЛ'), ('Л/П', 'Л/П')], max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.category', verbose_name='Категорія:')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('index_load', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.indexload', verbose_name='Індекс навантаження:')),
                ('index_speed', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.indexspeed', verbose_name='Індекс швидкості:')),
                ('model', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.brandmodel', verbose_name='Модель:')),
            ],
            options={
                'verbose_name': 'historical tire',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
