# Generated by Django 3.2.7 on 2022-08-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_historicaltire'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltire',
            name='qr_code',
            field=models.TextField(blank=True, help_text='QR-code генерується автоматично', max_length=100),
        ),
        migrations.AddField(
            model_name='tire',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR-code генерується автоматично', upload_to='media/qr_codes'),
        ),
    ]
