# Generated by Django 4.1 on 2022-08-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220806_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltire',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tire', 'verbose_name_plural': 'historical tires'},
        ),
        migrations.AlterField(
            model_name='historicaltire',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR-code генерується автоматично', null=True, upload_to='qr_codes'),
        ),
    ]
