# Generated by Django 4.1 on 2022-08-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_quickorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickorder',
            name='phone',
            field=models.IntegerField(verbose_name='телефон'),
        ),
    ]
