# Generated by Django 4.1 on 2022-08-25 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_quickorder_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickorder',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Шипы'),
        ),
        migrations.AddField(
            model_name='quickorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quickorder',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
