# Generated by Django 4.1 on 2022-08-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_quickorder_complete_quickorder_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickorder',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Виконаний'),
        ),
    ]
