# Generated by Django 4.1 on 2022-09-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_quickorder_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quickorder',
            options={'ordering': ['complete'], 'verbose_name': 'Швидке замовлення', 'verbose_name_plural': 'Швидкі замовлення'},
        ),
        migrations.AddField(
            model_name='quickorder',
            name='status',
            field=models.CharField(blank=True, choices=[('-', '-'), ('Забрав', 'Забрав'), ('Відмова', 'Відмова')], default='-', max_length=50, null=True),
        ),
    ]
