# Generated by Django 4.1 on 2022-09-08 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_alter_quickorder_options_quickorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickorder',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_order_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
