# Generated by Django 4.1 on 2022-11-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_quickorder_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickorder',
            name='comment',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quickorder',
            name='status',
            field=models.CharField(blank=True, choices=[('-', '-'), ('Бронь', 'Бронь'), ('Не відповів', 'Не відповів'), ('Забрав', 'Забрав'), ('Відмова', 'Відмова')], default='-', max_length=50, null=True),
        ),
    ]
