# Generated by Django 4.1 on 2023-02-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_quickorder_comment_alter_quickorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltire',
            name='articul',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='tire',
            name='articul',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Артикул'),
        ),
    ]
