# Generated by Django 4.1 on 2023-02-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_historicaltire_articul_tire_articul'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=120, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, max_length=64, verbose_name='SEO Title'),
        ),
    ]
