# Generated by Django 4.1 on 2023-03-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_quickorder_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickorder',
            name='manager',
        ),
    ]
