# Generated by Django 4.1 on 2023-03-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_quickorder_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickorder',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
