# Generated by Django 4.1 on 2023-03-15 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0018_quickorder_manager_alter_quickorder_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickorder',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Якщо клієнт зареєстрований, висвічується номер телефону зареєстрованого клієнта.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='quickorder',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Менеджер вибирається тільки в тому випадку, коли клієнт не зареєстрований, і оформив швидке замовлення. Якщо клієнт зареєстрований, менеджер присвоюється в особистій інформації про клієнта', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_order_manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
    ]
