# Generated by Django 4.1 on 2023-04-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstorageinfo',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstorageinfo',
            name='payee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='payee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
