# Generated by Django 4.1 on 2023-04-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
