# Generated by Django 4.1 on 2023-04-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tire', '0002_client_slug_historicalclient_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstorageinfo',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
