# Generated by Django 4.1 on 2023-04-27 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tire', '0003_alter_historicalstorageinfo_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstorageinfo',
            name='quantity_days',
            field=models.CharField(default=1, max_length=255, verbose_name='Кількість днів:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storageinfo',
            name='quantity_days',
            field=models.CharField(default='1', max_length=255, verbose_name='Кількість днів:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_client_tire', to='storage_tire.client', verbose_name='Клієнт:'),
        ),
    ]
