# Generated by Django 4.1 on 2023-04-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tire', '0004_historicalstorageinfo_quantity_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstorageinfo',
            name='quantity_days',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кількість днів:'),
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='quantity_days',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кількість днів:'),
        ),
    ]
