# Generated by Django 4.1 on 2023-04-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tire', '0005_alter_historicalstorageinfo_quantity_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstorageinfo',
            name='package',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storageinfo',
            name='package',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
