# Generated by Django 4.1 on 2023-04-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tire', '0007_alter_historicalstorageinfo_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstorageinfo',
            name='package',
        ),
        migrations.RemoveField(
            model_name='storageinfo',
            name='package',
        ),
    ]
