# Generated by Django 4.1 on 2023-04-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tire', '0008_remove_historicalstorageinfo_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstorageinfo',
            name='package',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='storageinfo',
            name='package',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
